wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1650619974
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      3:
      - 13
      4: 3.7.11
      5: 0.12.11
      6: 4.16.2
      8:
      - 3
      - 5
action_embed_size:
  desc: null
  value: 128
att_vec_size:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 1
beam_size:
  desc: null
  value: 5
clip_grad:
  desc: null
  value: 5.0
col_embed_size:
  desc: null
  value: 300
column_att:
  desc: null
  value: affine
column_pointer:
  desc: null
  value: true
cuda:
  desc: null
  value: true
data_dir:
  desc: null
  value: data\spider
data_set:
  desc: null
  value: spider
decode_max_time_step:
  desc: null
  value: 40
dropout:
  desc: null
  value: 0.3
embed_size:
  desc: null
  value: 300
encoder_pretrained_model:
  desc: null
  value: facebook/bart-base
eval_every_n_steps:
  desc: null
  value: 1000
exp_name:
  desc: null
  value: exp
hidden_size:
  desc: null
  value: 300
loss_epoch_threshold:
  desc: null
  value: 50
lr_base:
  desc: null
  value: 0.001
lr_connection:
  desc: null
  value: 0.0001
lr_transformer:
  desc: null
  value: 2.0e-05
max_grad_norm:
  desc: null
  value: 1.0
max_seq_length:
  desc: null
  value: 1024
model_output_dir:
  desc: null
  value: experiments
model_to_load:
  desc: null
  value: null
num_epochs:
  desc: null
  value: 5.0
pretrain_epochs:
  desc: null
  value: 0
readout:
  desc: null
  value: identity
run_spider_evaluation_after_epoch:
  desc: null
  value: false
scheduler_gamma:
  desc: null
  value: 0.5
seed:
  desc: null
  value: 90
sketch_loss_weight:
  desc: null
  value: 1.0
toy:
  desc: null
  value: false
type_embed_size:
  desc: null
  value: 128
